### ISSUE TITLE
Running commands from the administrator

### ISSUE THREAD

**Issue by egorsmkv** [tdenniston/bish#28]
I would like to ask how it will be implemented?

You can make a semblance of annotations:

``` bash
@root
cd('/home');
```

Or like this:

``` bash
cd('/home') as root;
```

This is a relevant question, I think, for many users.

**Comment by noahmorrison** [comment]
By executing the entire file as sudo

```
$ sudo bish -r /root/bin/example.bish
```

This is how you would do it in bash as well, unless I'm misunderstanding something.

**Comment by egorsmkv** [comment]
@noahmorrison I mean the execution of certain commands from the administrator.

**Comment by noahmorrison** [comment]
@eg0r I'm confused, could you show me an example in bash?

Do you mean something like this?

``` bash
sudo -u root $cmd
sudo -k
```

**Comment by egorsmkv** [comment]
@noahmorrison Yes. Perform certain commands defined by the user.

Excuse me, I use a translator because I have weak English.

**Comment by noahmorrison** [comment]
It's fine, I might play around with bash implementations this afternoon. I personally like the `@root` more than the `as root`. Running full blocks as a user might be something we look at as well.

```
@root {
    @(yaourt -Syua);
    echo("this is also run as root");
}
```

**Comment by egorsmkv** [comment]
It would be wonderful.

**Comment by tdenniston** [comment]
Overall, this is a good idea. One thing is that the syntax should probably be '@su' for superuser instead of '@root'.

It would also be good to come up with a unified syntax for this and executing normal external commands.  For example, we might do `@su(...);` to match the `@(...);` syntax. The idea of executing whole external blocks is good too, and it would be fairly straightforward to allow multiple statements within the parens, separated by semicolons.

**Comment by egorsmkv** [comment]
@tdenniston Need to make the operator that selects the user, not just root.

E.g.: `@root(...);` or `@my-mom(...);`.

To execute multiple commands:

``` sh
@my-dad {
   cd(...);
   # ...
}
```
